import Head from 'next/head'
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import CatComponent, { LinkArrow } from "@/components/Icons";
import React from "react";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
    return (
        <>
            <Head>
                <title>Gustavo Ariel Gamarra Rojas</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <TransitionEffect />

            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0 md:-mt-16 sm:pt-8 lg:-mt-20 xl:pt-0 sm:-mt-32 sm:pb-0 xs:-mt-32 xs:py-0">
                    <div className="flex items-center justify-between w-full lg:flex-col sm:pb-24">

                        {/* Imagen circular con borde verde menta */}
                        <div className="w-1/2 lg:w-full md:mb-8 md:w-4/5 xs:w-full sm:mb-0 flex justify-center">
                            <div className="w-2400Passion Fuels purpose!  h-2400 md:w-48 md:h-48 sm:w-40 sm:h-40 rounded-full overflow-hidden ">
                                <Image
                                    src={profilePic}
                                    alt="Gustavo Gamarra"
                                    className="w-full h-full object-cover"
                                    priority
                                />
                            </div>
                        </div>

                        {/* Texto y botón de contacto */}
                        <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
                            <AnimatedText
                                text="Gustavo Ariel Gamarra Rojas"
                                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
                            />
                            <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                                Como Analista UX en Datapar S.A., he impulsado la innovación en la visualización de datos, combinando mi experiencia en Matplotlib y Pandas para crear soluciones gráficas intuitivas que facilitan la toma de decisiones.
                                Mi formación en Análisis y Desarrollo de Software en Uniamérica (culminando en 2025) me permite abordar proyectos de manera integral, desde la exploración de datos hasta la creación de interfaces interactivas.
                            </p>
                            <div className="flex items-center self-start mt-2 lg:self-center">
                                <Link
                                    href="/dummy.pdf"
                                    target="_blank"
                                    className="flex items-center bg-dark text-light
                                       py-2.5 px-6 mr-4 rounded-lg text-lg font-semibold
                                       hover:bg-light hover:text-dark border-2 border-solid border-transparent
                                       hover:border-dark transition-all ease duration-300 dark:bg-light dark:text-dark
                                       dark:hover:bg-dark dark:hover:text-light dark:hover:border-light
                                       md:p-2 md:px-4 md:text-base"
                                    download
                                >
                                    Curriculum <LinkArrow className={"w-6 ml-1"} />
                                </Link>
                                <Link
                                    href="mailto:gugaro8@gmail.com"
                                    passHref
                                    legacyBehavior
                                >
                                    <a className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base">
                                        Contacto
                                    </a>
                                </Link>
                            </div>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    );
}
